### ISSUE TITLE
failed to fetch from registry: serialport/1.0.4

### ISSUE THREAD

**Issue by berusnet** [nneves/R2C2_WebInterface#10]
Hi ,
when I try last step "npm install" I got this error 

pi@raspberrypi ~/R2C2_WebInterface $ npm install
npm http GET https://registry.npmjs.org/union/0.3.0
npm http GET https://registry.npmjs.org/flatiron/0.2.8
npm http GET https://registry.npmjs.org/ecstatic/0.1.6
npm http GET https://registry.npmjs.org/serialport/1.0.4

npm ERR! Error: failed to fetch from registry: serialport/1.0.4
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:$
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client$
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:$
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256$
npm ERR! You may report this log at:
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/R2C2_WebInterface/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.18.7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/R2C2_WebInterface
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: serialport/1.0.4
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/R2C2_WebInterface/npm-debug.log
npm not ok
pi@raspberrypi ~/R2C2_WebInterface $ nano npm-debug.log
  GNU nano 2.2.6             File: npm-debug.log

Thanks in advance :)

**Comment by nneves** [comment]
Hum, looks strange! Could this be network related, have you tried again?

If this doesn't work, try to change the serialport package version to "*":
https://github.com/nneves/R2C2_WebInterface/blob/master/package.json
"serialport": "*"

Not sure if you would required: sudo npm install 

Bare in mind that this project was forked and refactored: 
https://github.com/nneves/3DPrinterInterface

Also are experimental projects, if you like to code javascript and node.js, feel free to make some changes , I haven't been active on this project for a while!
If you just want a good web-interface for your printer, have a look at Gina's Octoprint, it's awesome:
http://octoprint.org/

**Comment by berusnet** [comment]
Thanks for your quick reply :)

 I tried Octoprint too , it run but can view the usbserial port.

Re-installed node the previous problem solved.
> serialport@1.0.4 install /home/pi/R2C2_WebInterface/node_modules/serialport
> node-gyp rebuild
installation "freeze" here ..
The main problem is that a can't install the virtual port in any way ..
 I will work on ..thanks and sorry for the disturb :)

**Comment by nneves** [comment]
Closing this issue, no time available to fix old projects!
